# -*- coding: utf-8 -*-
"""GIO_desafio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXLdFsLRbyoo02m6HXYexS2TMZvQCOGu
"""

import pandas as pd
import json

sdw2023_api_url = 'https://sdw-2023-prd.up.railway.app'

users = [
    {'id': 1, 'nome': 'Naruto', 'news': []},
    {'id': 2, 'nome': 'Hinata', 'news': []}
]

print("usuario carregados: ")
users

def generate_ai_news(user):
    return f"{user['nome']}, investir é essencial para construir um futuro financeiro sólido."

for user in users:
    news = generate_ai_news(user)
    user['news'].append({
        "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
        "description": news
    })

print("Mensagens geradas:")
users

for user in users:
    news = generate_ai_news(user)
    print(news)
    user['news'].append({
        "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
        "description": news
    })

with open("users_with_news.json", "w", encoding="utf-8") as f:
    json.dump(users, f, ensure_ascii=False, indent=2)

print("Arquivo JSON salvo com sucesso!")

import json
print(json.dumps(users, indent=2, ensure_ascii=False))

print("usuario carregados: ")
users